failChance: 0.1

spring:
  sleuth:
#    propagation-keys:
#    - x-request-id
#    - x-ot-span-context
    web:
      additional-skip-pattern: /liveness|/readiness|/metrics
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:application;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver